import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";
import React from "react";
import Navbar from "../../component/navbar/Navbar";
import "./termscondition.css";
import LooterFooter from "../../component/lowerfooter/LooterFooter";

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

const TermCondition = () => {
  return (
    <Box sx={{ flexGrow: 1 }}>
      <Grid container>
        <Grid item xs={12}>
          <Item style={{ boxShadow: "none", backgroundColor: "#d4e4e5" }}>
            <Navbar />
          </Item>
        </Grid>
        <Grid item xs={12}>
          <Item
            style={{
              boxShadow: "none",
              backgroundColor: "#d4e4e5",
              height: "25vh",
              justifyContent: "center",
              alignItems: "center",
              display: "flex",
            }}
          >
            <h1 className="term_heading">Terms & Conditions</h1>
          </Item>
        </Grid>

        <Grid item xs={12}>
          <Item
            style={{
              boxShadow: "none",
              backgroundColor: "aliceblue",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Grid item  className='term_content'> 
              <Item
                style={{
                  boxShadow: "none",
                  backgroundColor: "white",
                  marginTop: "4%",
                  marginBottom: "4%",
                }}
              >
                <p
                  className="term_paragraph"
                >
                  These usual conditions of use employ to all services regulated
                  by AAOO CHALE (defined herein below). AAOO CHALE owns and
                  operates the Site (defined herein below) in India. This
                  application is operated by{" "}
                  <b>
                    DREAM PLATFORMS PRIVATE LIMITED (CIN: U63030UP2022PTC167593)
                  </b>{" "}
                  having registered office at
                  <b>
                    {" "}
                    Unit 1111, 11th floor skyline Plaza-1Tower-9, situated at
                    Sushant Golf city Sultanpur road Lucknow UP 226002 IN
                  </b>
                  <br />
                  <br />
                  These terms and conditions (“User Terms”) apply to your visit
                  to and use, of the Site whether through a computer or a mobile
                  phone, the Service and the Application, as well as to all
                  information, recommendations and or services provided to you
                  on or through the Site, the Service and the Application. This
                  document is an electronic record in terms of Information
                  Technology Act, 2000 and rules there under as applicable and
                  the provisions pertaining to electronic records in various
                  statutes as amended by the Information Technology Act, 2000.
                  This electronic record is generated by a computer system and
                  does not require any physical or digital signatures. By
                  clicking on the “I ACCEPT” button or by using AAOO CHALE, You
                  are consenting to be bound by these User Terms. PLEASE ENSURE
                  THAT YOU READ AND UNDERSTAND ALL THESE USER TERMS BEFORE YOU
                  USE THE SITE. If You do not accept any of the User Terms, then
                  please do not use the Site or avail any of the services being
                  provided therein.
                  <br />
                  <br />
                  By accepting these T&Cs, you also allow AAOO CHALE to send you
                  promotional emails and SMS alerts from time to time.
                  <br />
                  <br />
                  <h4 className="term_heading1">
                    Descriptions and Limitations
                  </h4>
                  <br />
                  "VEHICLE pooling" refers to the method of a VEHICLE Owner
                  sharing their Vehicle with a Co-Traveler on a Trip in exchange
                  for a Cost Contribution;
                  <br />
                  <br />
                  The term "Principles" refers to these General Terms and
                  conditions of Use, the AAOO CHALE Good Conduct Charter, and
                  the Privacy Policy as made known on the Site.
                  <br />
                  <br />
                  The sum agreed upon between the VEHICLE Owner and the
                  Co-Traveler in association with the Journey and payed by the
                  Co-Traveler as their share towards the Journey's costs is
                  referred to as the "Cost Participation." <br />
                  <br />
                  "Co-Traveller" or "Traveler" refers to a USER who approves a
                  Vehicle Owner's offer to transport them, as well as any more
                  passengers they have in the Vehicle during the Journey.
                  <br />
                  <br />
                  A USER who offers to share a VEHICLE journey with a
                  Co-Traveller through the Site is referred to as a "VEHICLE
                  Owner" or "Driver" in exchange for the Cost Sharing. <br />
                  <br />
                  A registered user of the Site is referred to as a "User."
                  <br />
                  <br />
                  The term "Journey" refers to a specific travel for which a
                  Vehicle Owner and a Co-Traveler have reached an agreement on a
                  transaction through the Site.
                  <br />
                  <br />
                  A USER's account with the Site that is utilised to access the
                  Service offered by AAOO CHALE through the Site is referred to
                  as a "User Account."
                  <br />
                  <br />
                  <h3 className="term_heading1">Acceptance of Terms</h3>
                  <br />
                  The Terms govern each and every use of the Site by a USER.
                  USERs agree to be bound by these Conditions and indicate their
                  full acceptance of them by using the Site.
                  <br />
                  <br />
                  If the Conditions are not fully acknowledged, access to the
                  Services will not be allowed. No USER may accept the
                  Conditions in whole or in part. A USER is not permitted to use
                  the Services if they do not accept the Conditions.
                  <br />
                  <br />
                  All USERS concur to abide by the Conditions and acknowledge
                  that the Privacy Policy may apply to the processing of their
                  personal data.
                  <br />
                  <br />
                  If a USER violates any of the Conditions, AAOO CHALE reserves
                  the right, but not the responsibility, to remove that USER's
                  User Account and suspend or terminate the Services provided to
                  that USER without prior notice.
                  <br />
                  <br />
                  According to the Indian Contract Act of 1872, these Conditions
                  are meant to establish legally enforceable rights and
                  responsibilities between USERs and AAOO CHALE.
                  <br />
                  <br />
                  <h3 className="term_heading1">ACCESSING THE SERVICE</h3>
                  <br />
                  User Account and Information Reliability
                  <br />
                  <br />
                  Each USER must set up a User Account and consent to give any
                  personal information needed by AAOO CHALE in order to utilise
                  the Services. USERs will be needed to supply information such
                  as their first and last names, age, title, a working phone
                  number, and email address. Only individuals who are at least
                  18 years old at the time of registration are permitted to use
                  the website.
                  <br />
                  <br />
                  USERs acknowledge and agree that any information they give to
                  AAOO CHALE during the creation of their user account or at any
                  other time must be truthful, accurate, full, and correct in
                  all material aspects. USERs also acknowledge that any
                  information they provide to AAOO CHALE or publish on the
                  website in connection with any journey, vehicle, or VEHICLE
                  sharing shall be true, accurate, and comprehensive.
                  <br />
                  <br />
                  USERs acknowledge and accept that AAOO CHALE will not verify
                  any information submitted by USERs on the Site or to a VEHICLE
                  Owner or Co-Traveler, as the case may be, in order to validate
                  its veracity. Any USER who submits information that is untrue,
                  incorrect, erroneous, misleading, or dishonest shall not be
                  held accountable for AAOO CHALE. USERs are only permitted one
                  User Account per USER, unless otherwise permitted by AAOO
                  CHALE. No User Account may be set up on someone else's behalf
                  or with the intention of impersonating them.
                  <br />
                  <br />
                  <h3 className="term_heading1">
                    No Business Activity and the Current Status of AAOO CHALE
                  </h3>
                  <br />
                  The Site and the Services are only capable of facilitating
                  private vehicle sharing between co-travelers and VEHICLE
                  owners. The use of the Services in any business or
                  professional setting, or to provide or accept vehicle sharing
                  for hiring, payment, or profit, is prohibited. Only vehicle
                  sharing in which the expense of the journey is split between
                  the co-traveler and the VEHICLE owner is permitted to be
                  offered or accepted through the usage of the Services.
                  <br />
                  <br />
                  VEHICLE Owners concur that they will not use any journey as a
                  means of profit, reward, or hiring. The Service and the Cost
                  Share may not be utilized to produce hiring fees, rewards, or
                  any other type of profit for the VEHICLE Owner; rather, they
                  may only be used to cover the VEHICLE Owner's expenditures.
                  The amount of the Cost Sharing, the kinds of Journeys a
                  VEHICLE Owner offers, the frequency of such Journeys, or the
                  mass of Co-Travelers VEHICLE ride do not provide the VEHICLE
                  Owner the right to profit. All activities, arrangements, and
                  services that are booked through the site as well as any extra
                  services or activities that may be arranged between the
                  VEHICLE owner and co-traveler through the site are covered by
                  this.
                  <br />
                  <br />
                  The Co-Traveler may not accept or request any additional
                  services from the VEHICLE Owner, including (without
                  limitation) package delivery, wait period, additional
                  drop-offs and pick-ups, and picking up more passengers,
                  whether in return for hiring fees, rewards, profit, or any
                  other reason (other than the Co-Traveler).
                  <br />
                  <br />
                  The VEHICLE Owner and Co-Traveler must pre-agree on all
                  Journeys, pickup places, and destinations through the web
                  page. VEHICLE Owners are not allowed to pick up Co-Travelers
                  from any location that has not been previously set up through
                  the Site with the Co-Traveller.
                  <br />
                  <br />
                  USERs are advised that utilizing the Services and offering
                  Journeys for employment, reward, or in a business or
                  professional capacity may void a VEHICLE Owner's insurance and
                  trigger retaliatory legal measures from the road transport
                  authorities. When a VEHICLE Owner violates these terms and
                  offers Services through the Site in a professional or
                  commercial capacity (potentially invalidating their
                  insurance), AAOO CHALE shall not be liable for any loss or
                  damage incurred by a USER as a result of that VEHICLE Owner's
                  contravention of any agreement with the Co-Traveler. AAOO
                  CHALE shall have no liability for any Journeys offered by
                  USERs in violation of the Conditions.
                  <br />
                  <br />
                  The Site and AAOO CHALE do not offer any transportation
                  services. The Site serves as a platform for USERs to
                  communicate and conduct business with one another. No
                  disruptions to Journeys, destinations, or timings are caused
                  by AAOO CHALE. The Co-Traveler and the VEHICLE Owner are
                  parties to the VEHICLE sharing arrangement. Neither is AAOO
                  CHALE a party to any agreement or transaction between USERs,
                  nor is AAOO CHALE responsible for any issue that arises in
                  connection with a booking made by USERs. As an agent for any
                  USER, AAOO CHALE is not now and never will be. Any violation
                  of these Terms will result in the immediate suspension of that
                  USER's User Account and possible restrictions on their
                  capability to use other Services.
                  <br />
                  <br />
                  <h3 className="term_heading1">
                    Forms of Reservations and Fees
                  </h3>
                  <br />
                  To make it easier for passengers to reserve seats, AAOO CHALE
                  provides its USERs with an online booking service (hence, the
                  "Booking Service").
                  <br />
                  <br />
                  Due to: I changes in the law that applies, (ii) market
                  practices or technological advancements, (iii) changes in the
                  business considerations underlying the Booking Services, and
                  (iv) other significant and compelling factors, AAOO CHALE
                  reserves the right to refuse to provide the Booking Service to
                  a Journey.
                  <br />
                  <br />
                  The number of USERs who are eligible to use the Booking
                  Service for any Journey may be restricted by AAOO CHALE based
                  on their class or other factors.
                  <br />
                  <br />
                  <h3 className="term_heading1">
                    How to reserve a VEHICLE for a journey:
                  </h3>
                  <br />
                  The VEHICLE Owner posts information about his or her Journey
                  on the website, including the date and time of the journey,
                  the location of the departure and destination, the cost
                  contribution per passenger, and any other pertinent travel
                  requirements. <br /> <br />
                  By clicking the "Book" button on the Site's homepage, the
                  Passenger reserves one or more seats in the vehicle for that
                  Journey (hence, the "Booking"). <br /> <br />
                  The Booking Confirmation, also known as the "Booking Email,"
                  will subsequently be sent by AAOO CHALE to the Driver and the
                  Passenger. A separate, legally enforceable agreement for
                  VEHICLE sharing related to the journey will be made between
                  the VEHICLE-Owner and Passenger after a booking confirmation
                  has been provided. <br /> <br />
                  USERs acknowledge that due to the nature of the service,
                  neither VEHICLE Owners nor Co-Travelers will have any recourse
                  against AAOO CHALE for any aspect of the transaction,
                  including cancellation, last-minute changes, failure on the
                  part of the VEHICLE Owner or the Co-Traveler to show up, or
                  non-payment of the Cost Contribution. In particular, the
                  VEHICLE Owner is accountable for getting payment from the
                  Co-Traveler throughout the journey. <br /> <br />
                  In order to manage the booking, AAOO CHALE will only conduct
                  the actions outlined above and not get in touch with the
                  parties. The respective VEHICLE Owner and Co-Traveler are
                  entirely responsible for managing the functioning of the
                  Journey (s). <br /> <br />
                  Please be aware that AAOO CHALE maintains the right to modify
                  any element of the Site or the Service, including by
                  introducing new services (which may have a fee associated with
                  them) or by removing any current Services or terms &
                  conditions. Although AAOO CHALE makes every effort to keep the
                  Site up and running, there may be periods when it is not, and
                  during those instances, services may be halted. If the Site is
                  unavailable, AAOO CHALE won't be accountable to any of the
                  USERs.
                  <br />
                  <br />
                  <h3 className="term_heading1">
                    VEHICLE Owner's Responsibilities
                  </h3>
                  <br />
                  They promise to secure a complete insurance coverage for the
                  VEHICLE, one that covers third-party responsibility and
                  insures the VEHICLE's passengers as well. <br /> <br />
                  That they'll arrive in the designated vehicle on time and at
                  the agreed-upon location. <br /> <br />
                  Any changes to the journey will be immediately communicated to
                  all other travellers. If one or more Co-Travelers have made
                  reservations and the VEHICLE Owner decides to alter any
                  feature of the Journey, the VEHICLE Owner is obligated to get
                  the consent of all Co-Travelers who have made reservations for
                  that Journey by contacting them. Co-Travelers are entitled to
                  a full refund if they decline the adjustment, and the VEHICLE
                  owner will not be compensated in any way. <br /> <br />
                  The VEHICLE Owner is always required to adhere to the Good
                  Conduct Standard. <br /> <br />
                  At least 30 minutes beyond the scheduled time, the VEHICLE
                  Owner must wait for the Co-Traveler at the pickup location
                  (however, the Co-Traveler is expected to be punctual). <br />{" "}
                  <br />
                  <h3 className="term_heading1">
                    Co-Traveler Responsibilities
                  </h3>
                  <br />
                  That the journey won't be used for any illegal, fraudulent, or
                  criminal activities. <br /> <br />
                  That they would show up on time and where previously agreed
                  upon with the VEHICLE owner; <br /> <br />
                  That if they must cancel a Journey, they will notify the
                  VEHICLE Owner or AAOO CHALE right away. <br /> <br />
                  that they would always abide by the Good Conduct Charter.{" "}
                  <br /> <br />
                  The Co-Traveler agrees to remain at the pickup location for
                  the VEHICLE Owner's arrival for a minimum of 30 minutes beyond
                  the scheduled arrival time. <br /> <br />
                  that they will provide the VEHICLE owner their cost share.{" "}
                  <br /> <br />
                  In the event that the Co-Traveler or VEHICLE Owner violates
                  any of these conditions or any other Conditions, AAOO CHALE
                  maintains the right to keep a record of the violation, publish
                  or reveal the violation on the USER's online profile, and
                  suspend or terminate the USER's access to the Site. <br />{" "}
                  <br />
                  They must make sure that everyone else travelling with them
                  complies with these conditions in sof ar as they apply to
                  Co-Travellers. <br /> <br />
                  <h3 className="term_heading1">INSURANCE</h3>
                  <br />
                  The Vehicle Owner consents and agrees to get and maintain
                  comprehensive insurance to protect themselves against
                  third-party responsibility, the passengers in their vehicle,
                  and the Journey they are offering or booking on the
                  website.The Vehicle Owner commits to showing the Co-Traveler
                  proof of the full validity of its insurance policy prior to
                  the Journey upon request and at the Vehicle Owner's
                  expense.The Co-Traveler has the right to request proof of the
                  Vehicle Owner's insurance, registration certificate (also
                  known as a "log book"), driving licence, and PUC certificate
                  at any time up until the end of the Journey. The Vehicle Owner
                  also guarantees that they will own or have the right to use
                  the vehicle and that it will have a valid PUC (Pollution Under
                  Control) certificate.
                  <br />
                  <br />
                  According to what Aaoo Chale understands, governmental
                  officials in India believe that a Co-Traveler who pays just
                  for their own travel expenditures is considered to be
                  travelling at no cost to the driver and is therefore protected
                  by comprehensive third-party insurance. However, Aaoo Chale
                  makes no guarantees or warranties in this regard, and it is
                  the Vehicle Owner's duty to confirm that their insurance
                  offers sufficient protection.
                  <br />
                  <br />
                  It is the responsibility of each Vehicle Owner and Co-Traveler
                  to verify with one another that the Vehicle Owner is protected
                  by a policy that is in effect.The Vehicle Owner must certify
                  that their insurance coverage covers all Co-Travelers and any
                  accidents or incidents that may arise during a journey, as
                  well as that they are permitted to Vehicle Co-Travelers.
                  <br />
                  <br />
                  The Vehicle Owner and the Co-Traveler are aware that typical
                  non-commercial insurance policies may decline to pay for loss
                  or damage if the Vehicle Owner made or attempted to make a
                  profit.
                  <br />
                  <br />
                  The Co-Traveler may not be charged anything other than the
                  Cost Contribution by the Vehicle Owner, and the Vehicle Owner
                  may not under any circumstances supply the Vehicle for hiring
                  or reward of any kind.
                  <br />
                  <br />
                  Therefore, the Vehicle Owner agrees to estimate their costs
                  (including fuel, tolls, maintenance, repairs, depreciation,
                  and insurance) and ensures that the total cost contributions
                  asked from their Co-Travelers will not cause the Vehicle to be
                  used for employment or reward.
                  <br />
                  <br />
                  The Vehicle Owner will be liable for any resulting financial
                  consequences, losses, and damages, and Aaoo Chale will never
                  be liable to the Vehicle Owner or the Co-Traveler in the event
                  that the Vehicle Owner does receive any hiring fees or rewards
                  or if the insurers reject or refuse to accept any claim
                  arising during a Journey for any other reason.
                  <br />
                  <br />
                  Aaoo Chale retains the right, but not the duty, to instantly
                  suspend a user's account, including any money visible on it,
                  and to report any professional activity to the appropriate
                  authorities.
                  <br />
                  <br />
                  Dispute Resolution among Users
                  <br />
                  <br />
                  An online service for resolving complaints may be offered to
                  Users by Aaoo Chale at its exclusive discretion. This service
                  has no legal effect. This service is provided at Aaoo Chale's
                  sole discretion and may be discontinued at any time; Aaoo
                  Chale is under no obligation to try to mediate disagreements.
                  <br />
                  <br />
                  <h3 className="term_heading1">
                    Verification of IDs and phone numbers
                  </h3>
                  <br />
                  By agreeing to the terms and conditions set forth herein, each
                  Member and any person wishing to register as a Member hereby
                  agrees and consents to the collection of their personal
                  identification documents by Aaoo Chale, including but not
                  limited to their passport, PAN Vehicle, and Aadhaar Vehicle
                  id, for the purpose of third party service providers verifying
                  the information contained therein. <br /> <br /> The Member
                  may validate their cell phone number in order to improve
                  credibility and guard against typos and incorrect numbers. By
                  giving Aaoo Chale their mobile phone number, the Member can
                  accomplish this. Subsequently, the Member will receive an SMS
                  with a 4-digit code that can be verified on the Site. Except
                  for any potential fees charged by a Member's mobile phone
                  operator for receiving the SMS, this service is free. <br />{" "}
                  <br />
                  <h3 className="term_heading1">
                    International travel and reservations
                  </h3>
                  <br />
                  Through the website, reservations for overseas journeys are
                  possible. Any journey that includes any travel outside of
                  India is considered an international journey. If a reservation
                  is made for a journey outside of India, the Vehicle owner must
                  make sure that their insurance policy supports such travel.
                  The vehicle owner must also make sure that their Vehicle
                  complies with all applicable laws and regulations in any
                  foreign country.
                  <br /> <br />
                  <h3 className="term_heading1">
                    Communications among Users
                  </h3>
                  <br />
                  In order to prevent fraud, provide customer service, enforce
                  agreements made with Aaoo Chale's Users (including the
                  Conditions), and ensure legal compliance, Aaoo Chale may
                  monitor, scan, and moderate the messages that Users send to
                  each other through the Site.For instance, Aaoo Chale may scan
                  and analyse communications received over the platform to
                  ensure that they don't contain any contact information or
                  referrals to other websites in order to prevent the
                  circumvention of its Booking Service.
                  <br />
                  <br />
                  The Member accepts that Aaoo Chale may, in its sole
                  discretion, evaluate, analyse, and moderate the messages sent
                  over the Site by using the Site and adopting the T&Cs. <br />{" "}
                  <br />
                  By using the site's messaging system, the Member agrees not to
                  create or transmit any messages that are against the law. In
                  particular, the Member agrees not to write or transmit any
                  messages that contain the following: <br /> <br />
                  • belongs to someone else and over which the Member has no
                  legal authority; <br /> <br />
                  • is blasphemously offensive, harassing, slanderous, vulgar,
                  or pornographic; <br /> <br />
                  • any injury to minors; <br /> <br />
                  • violates any intellectual property rights (patents,
                  trademarks, copyrights, etc.); <br /> <br />
                  • violates any already applicable law; <br /> <br />
                  • misleading the addressee about the source of the messages or
                  sending any information that is blatantly insulting or ominous
                  in character; <br /> <br />
                  • pretends to be someone else; <br /> <br />
                  • contains computer viruses that restrict the use of all
                  available resources; <br /> <br />
                  • threatens India's unity, integrity, defence, security, or
                  sovereignty, cordial relations with other countries, or public
                  order, or encourages the commission of any crime that could be
                  prosecuted, obstructs the investigation of any crime, or is
                  offensive to any other country. <br /> <br />
                  Additionally, the Member agrees to send messages only in
                  connection with the reservation of Vehicle-sharing services
                  and in accordance with the objectives of this website. The
                  Member promises not to use the messages for any private or
                  secret communications. <br /> <br />
                  If it becomes apparent through the moderation of the messages
                  submitted by the Member that s/he does not comply with the
                  Conditions and/or applicable legislation, Aaoo Chale reserves
                  the right to filter or delete the communications and suspend
                  or terminate the Member's User Account and access to the Site.{" "}
                  <br /> <br />
                  Making Contact with Users <br /> <br />
                  Each Member hereby agrees and grants permission to Aaoo Chale
                  to interact with them by phone calls, text messages, emails,
                  and any other methods that Aaoo Chale may deem appropriate by
                  accepting the terms and conditions included above. Such
                  contacts with Users may be recorded using the technical
                  assistance offered by third parties for training, quality
                  control, and to keep Users frequently informed about the
                  services of Aaoo Chale. <br /> <br />
                  <br /> <br />
                  <h3 className="term_heading1">LIABILITY DISCLAIMER</h3>
                  <br />
                  Before making any agreements with other Users through the
                  Site, Users may access the Services on the Site at their own
                  risk and at their own discretion. Users ' actions, inactions,
                  and violations of the terms, representations, or warranties by
                  Users are their own responsibility and are not the
                  responsibility of Aaoo Chale. Aaoo Chale expressly disclaims
                  all duty and responsibility for any and all consequences
                  resulting from the use of the Site.
                  <br />
                  <br />
                  In relation to Journeys, the accuracy, dependability, and
                  completeness of information provided by Users, or the content
                  (including specifics of the Journey and Cost Contribution) on
                  the Site, Aaoo Chale expressly disclaims any warranties or
                  representations (express or implied). While Aaoo Chale will
                  take steps to ensure that the content of the Site is accurate,
                  all content and information are supplied "as is" and "where
                  is” without any kind of warranty. None of the Users using the
                  Site's Services are supported or endorsed by Aaoo Chale,
                  either implicitly or expressly.
                  <br />
                  <br />
                  In the absence of fault on the part of Aaoo Chale, neither the
                  Vehicle Owner nor the Co-Traveler will be entitled to
                  compensation from Aaoo Chale since it is not a party to any
                  agreement between them.
                  <br />
                  <br />
                  Aaoo Chale is not responsible for any loss or damage brought
                  on by:
                  <br />
                  <br />
                  • A Member providing incorrect, deceptive, inaccurate, or
                  incomplete information;
                  <br />
                  <br />
                  • The journey's cancellation by a driver or fellow traveller;
                  <br />
                  <br />
                  • Any failure to pay a Cost Contribution (for the
                  complimentary service without a reservation);
                  <br />
                  <br />
                  • Any dishonesty, deceit, duty violation, or violation of any
                  of these terms by a Vehicle owner or fellow traveller before,
                  during, or after a journey.
                  <br />
                  <br />
                  • Except in cases of fraud, willful concealment, or theft,
                  Aaoo Chale will not be liable to any Member for any business,
                  financial, or economic loss, or for any consequential or
                  indirect loss such as lost reputation, lost bargain, lost
                  profit, lost of anticipated savings, or lost opportunity
                  arising as a result of the services provided by Aaoo Chale.
                  <br />
                  <br />
                  • For any losses related to any Journey, Aaoo Chale's
                  obligation to any Member is limited to INR 1,000. (Indian
                  Rupees One Thousand only).
                  <br />
                  <br />
                  • If a claim about a Journey is not reported to Aaoo Chale
                  within three months of the Journey's completion, Aaoo Chale
                  will not be liable to any Member in relation to such Journey.
                  <br />
                  <br />
                  • Users acknowledge that the limitations on Aaoo Chale's
                  responsibility set out above are acceptable given that Vehicle
                  Owners are required to have sufficient insurance to cover a
                  Journey and that Aaoo Chale's service is restricted to
                  connecting Vehicle Owners and Co-Travelers and cannot oversee
                  any Journey.
                  <br />
                  <br />
                  <h3 className="term_heading1">RELEASE AND INDEMNITY</h3>
                  <br />
                  Users agree to defend, indemnify, and hold harmless Aaoo
                  Chale, its subsidiaries, affiliates, and each of their
                  officers, directors, agents, and employees from any claim,
                  demand, action, or penalty brought by a third party due to or
                  arising out of a member's violation of these Conditions or any
                  document incorporated by reference, or from that member's
                  violation of any law, rule, regulation, or the rights of a
                  third party, including reasonable attorney's fees.
                  <br />
                  <br />
                  Users expressly waive any claims or demands that they may have
                  in this regard under any statute, contract, or other legal
                  theory and release Aaoo Chale and/or its affiliates and/or any
                  of its officers and representatives from any cost, damage,
                  liability, or other consequence of any of the actions or
                  inactions of the Users.
                  <br />
                  <br />
                  <h3 className="term_heading1">TERMS IN GENERAL</h3>
                  <br />
                  Relationship
                  <br />
                  <br />
                  No agreement made between Users and Aaoo Chale shall or be
                  construed as constituting an agency, partnership, joint
                  venture, or other arrangement of a similar nature between
                  Users and Aaoo Chale.
                  <br />
                  <br />
                  Termination or Revocation of Site Access
                  <br />
                  <br />
                  Text, graphics, logos, button icons, images, audio clips,
                  digital downloads, data compilations, and software that are
                  part of the Site's format and content are the property of Aaoo
                  Chale, its affiliates, or its content suppliers and are
                  protected by Indian and international copyright, author's
                  rights, and database rights laws.
                  <br />
                  <br />
                  Any registered and unregistered trademarks (whether owned or
                  licenced to Aaoo Chale) that appear on the Site are subject to
                  all rights reserved.
                  <br />
                  <br />
                  Without the express written authorization of Aaoo Chale, the
                  Site or any part of the Site may not be replicated,
                  duplicated, copied, sold, resold, visited, or otherwise used
                  for any commercial purpose. Without the express written
                  approval of Aaoo Chale, no one is permitted to repeatedly
                  extract and/or reuse any of the materials of the Site. In
                  particular, it is expressly forbidden to extract any
                  significant portions of this Site for later use using data
                  mining, robots, or similar data collection and extracting
                  techniques.
                  <br />
                  <br />
                  Users' Contributions to the Site's Content
                  <br />
                  <br />
                  Users expressly grant Aaoo Chale a licence to display the
                  content and use it for any of our other business purposes by
                  displaying content on this Site.
                  <br />
                  <br />
                  Users of this website are specifically requested not to
                  publish any offensive, deceptive, or defamatory content or any
                  content that violates the intellectual property rights of any
                  third party (e.g. copyright). Any such content that violates
                  Aaoo Chale's policies will subject the member who posted it to
                  personal duty for any resulting damages or other liabilities.
                  The member also undertakes to hold Aaoo Chale harmless for any
                  liability it may incur as a result of any such content.
                  However, Aaoo Chale will take all reasonable steps to get any
                  copyrighted content removed from the Site as soon as it is
                  discovered.
                  <br />
                  <br />
                  Related Sites
                  <br />
                  <br />
                  Any information that appears on the Site or on the partner
                  websites may be reproduced by Aaoo Chale.
                  <br />
                  <br />
                  In particular, advertisements posted on a site Aaoo Chale
                  maintains or co-maintains may be duplicated on other sites
                  Aaoo Chale maintains or co-maintains or those of third
                  parties.
                  <br />
                  <br />
                  <h3 className="term_heading1">TERMS IN GENERAL</h3>
                  <br />
                  These agreements will be governed by Indian law, and the
                  courts in Lucknow will have jurisdiction over any issues
                  relating to these conditions.
                </p>
              </Item>
            </Grid>
          </Item>
          <LooterFooter ht="100vh" />
        </Grid>
      </Grid>
    </Box>
  );
};

export default TermCondition;
